### ISSUE TITLE
image captions

### ISSUE THREAD

**Issue by lfoppiano** [TWMC/Website#2]
I'm wondering whether the caption are working, looking at the content project it seems that many captions have been generated, however are they working? I don't see how to do that from the content writing interface

**Comment by nishad** [comment]
Image captions were removed from the current website front-end since it was missing or incomplete for most of the images. However, captions are still maintained and improved for the images and hopefully, in the next major update, we can start showing them again for gallery slideshows. 

A caption can be edited from the content panel as a property of the image fie. 
Please see this demonstration [1] and follow the mouse pointer.

[1] https://cl.ly/e08b1e/image-caption-example.gif

**Comment by lfoppiano** [comment]
Right, great! I'll generate the captions then, we'll deal with them later
